project:
  type: website
  output-dir: docs

website:
  title: "Robinson Preserve Sport Fish"
  navbar:
    background: primary
    right:
      - href: index.qmd
        text: Home
      - text: About
        menu:
        - href: preserve.qmd
          text: Robinson Preserve
        - sidebar:tagging
      - updates.qmd
      - data.qmd
      - contact.qmd
  sidebar:
    - id: tagging
      title: "Tagging"
      style: "docked"
      background: light
      contents:
        - tagging/importance.qmd
        - tagging/works.qmd
        
        
        
        

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

editor: visual

