---
title: Robinson Preserve Sportfish Tagging Project
toc: false
sidebar: false
format:
  html:
    css: styles_splash.css
    anchor-sections: false
    title-block-banner: images/robinson3.jpeg
---

## Tracking juvenile sport fish movement from a habitat restoration site to fished populations of Tampa Bay

Many commercially and recreationally important fishes use estuarine habitats as juvenile nursery grounds. However, many of these habitats are threatened by a number of stressors, including rising sea levels and increasing urbanization. Restoration and preservation of affected juvenile habitats can help support adult populations.

```{r}
#| echo: false
#| warning: false
library(tidyverse)
library(sf)
library(mapview)
library(ggpubr)
library(png)
library(icons)

#### Prep spatial data layers ####

# read in Tampa Bay Shoreline shapefile
TBshore <- st_read('shapefiles/Tampa_Bay_Shoreline.shp', quiet = T) %>%
  st_transform(4326)

# read in Robinson Preserve outline polygon from Manatee County
preservedat <- st_read('shapefiles/Parks_and_Preserves.shp', quiet = T) %>%
  filter(NAME == 'Robinson Preserve') %>%
  select(NAME, TOTADDRESS, ZIPCODE, PARK_TYPE, ACREAGE, MANAGEMENT, OWNER_NAME, geometry)
preservedat.shp <- preservedat %>%
  st_transform(4326)
  
# the county shapefile is in WGS 84 and is a multipolygon

# read in Robinson Preserve expansion project outline polygon
expansiondat <- st_read('shapefiles/RobPres_Expansion_Poly.shp', quiet = T) %>%
  select(Entity, Layer, DocName, DocType, geometry) %>%
  #need to transform from NAD83 to WGS 84
  st_transform(4326)

#read in FIM pond outlines
ponddat <- st_read('shapefiles/Robinson_Preserve.shp', quiet = T) %>%
  mutate(Pond = str_sub(FolderPath, 24, 29)) %>%
  mutate(Type = case_when(Pond %in% c("Pond_6", "Pond_7") ~ "Natural",
                          TRUE ~ "Restored")) %>%
  #group by ponds and make them into polygon outlines
  group_by(Pond, Type) %>%
  summarise() %>%
  st_cast("POLYGON") %>%
  #for the outer polygon
  st_convex_hull()
# ponddat
# the FIM pond outlines are WGS 84 and are points

#pond outlines, as points, are also readable as individual layers from
#test <- st_read("Robinson_Preserve_2019.final.kml")

#locations of water loggers installed during restoration monitoring (different grant than acoustics)
loggerdat <- read.csv("shapefiles/RobPres_WaterLogger_loc.csv", header = T, stringsAsFactors = F)
logger.shp <- loggerdat %>%
  filter(Logger.. != 31) %>%
  select(Logger.Type, Pond = Location, Notes, LAT_DD, LONG_DD) %>%
  #specify lat/long and the WGS coord system as 4326
  st_as_sf(coords = c('LONG_DD', 'LAT_DD'), crs = 4326)
# logger.shp

#POTENTIAL locations of acoustic receivers
receiverdat <- read.csv("shapefiles/RobPres_PotAcousticReceiver_loc.csv", header = T, stringsAsFactors = F)
receiver.shp <- receiverdat %>%
  #specify lat/long and the WGS coord system as 4326
  st_as_sf(coords = c('LONG_DD', 'LAT_DD'), crs = 4326)
# receiver.shp

#appprocimate location of Rob Preserve entry/exit points
openingdat <- read.csv("shapefiles/RobPres_IngressEgress_loc.csv", header = T, stringsAsFactors = F)
opening.shp <- openingdat %>%
  #specify lat/long and the WGS coord system as 4326
  st_as_sf(coords = c('LONG_DD', 'LAT_DD'), crs = 4326)
# opening.shp

#### Interactive Mapview Map ####
mapviewOptions(basemaps = c("Esri.WorldImagery", "OpenStreetMap"),
               legend.pos = "topright")
mapview(preservedat, col.regions = "lightgreen", alpha.regions = 0.2, layer.name = "Robinson Preserve") +
  mapview(ponddat, col.regions = "lightblue", layer.name = "Waterbodies") +
  mapview(opening.shp, zcol = "Type", col.regions = c("Red", "Black"),
          alpha.regions = 10, cex = 5, layer.name = "Potential Exit/Entry Points")
  # mapview(logger.shp, col.regions = "blue", cex = 4.5, layer.name = "Water_Air Loggers") +
  # mapview(receiver.shp, col.regions = "yellow", cex = 8, alpha.regions = 10, layer.name = "Possible Receiver Locations")


#### Static Map ####
## NEED TO WORK ON THIS ##
#set fill colors in order used

#let's combine all point data to make a simple legend
pointdat <- read.csv("shapefiles/RobPres_pointstructures.csv", header = T, stringsAsFactors = F)
pointdat$Structure_Type <- factor(pointdat$Structure_Type, levels = c("Main ingress/egress",
                                                                      "Mosquito ditching",
                                                                      "Water logger",
                                                                      "Air logger",
                                                                      "Acoustic receiver"),
                                  labels = c("Main ingress/egress",
                                             "Mosquito ditch ingress/egress",
                                             "Water logger",
                                             "Air logger",
                                             "Acoustic receiver"))
pointdat.shp <- pointdat %>%
  #specify lat/long and the WGS coord system as 4326
  st_as_sf(coords = c('LONG_DD', 'LAT_DD'), crs = 4326)

# pallette <- c("red", "black", "blue", "pink", "yellow")
# shapes <- c(17, 17, 19, 13, 7)
# 
# p <- ggplot(data = TBshore) +
#   geom_sf(data = subset(TBshore, ATTRIBUTE == "LAND", select = c("OBJECTID", "ATTRIBUTE", "geometry")), fill = "light gray") +
#   geom_sf(data = subset(TBshore, ATTRIBUTE == "WATER", select = c("OBJECTID", "ATTRIBUTE", "geometry")), fill = "light blue") +
#   geom_sf(data = preservedat, fill = "light green", color = "dark green", alpha = 0.5) +
#   geom_sf(data = ponddat, fill = "light blue") +
#   geom_sf(data = pointdat.shp, aes(col = Structure_Type, shape = Structure_Type), size = 3.5) +
#   scale_color_manual(values = pallette) +
#   scale_shape_manual(values = shapes) +
#   coord_sf(xlim = c(-82.692, -82.65), ylim = c(27.49, 27.53), expand = FALSE) +
#   theme(
#     panel.background = element_rect(fill = "transparent"), # bg of the panel
#     plot.background = element_rect(fill = "transparent", color = NA), # bg of the plot
#     panel.grid.major = element_blank(), # get rid of major grid
#     panel.grid.minor = element_blank(), # get rid of minor grid
#     legend.background = element_rect(fill = "transparent"), # get rid of legend bg
#     legend.box.background = element_rect(fill = "transparent") # get rid of legend panel bg
#   )
# 
# p
# 
# 
# ggsave(p, filename = "test1.png",  bg = "transparent")

#### A better option for printing/saving to a static map ####
# mapviewOptions(basemaps = c("Esri.WorldImagery"),
#                legend.pos = "topright")
# mapview(preservedat, color = "lightgreen", lwd = 3, col.regions = "lightgreen", alpha.regions = 0.02,
#         layer.name = "Robinson Preserve", legend.opacity = 1) +
#   mapview(expansiondat, color = "lightcyan3", lwd = 3, col.regions = "lightcyan3", alpha.regions = 0.05,
#           layer.name = "Restoration Phase IIB", legend.opacity = 1) +
#   #mapview(ponddat, col.regions = "lightblue", layer.name = "Ponds") +
#   mapview(pointdat.shp, zcol = "Structure_Type", 
#           col.regions = c("red", "orange", "blue", "pink", "yellow"),
#           layer.name = "Structure Type",
#           alpha.regions = 10,
#           legend.opacity = 1)
```

The Robinson Preserve Sport Fish Tagging Project was initiated to determine the extent to which the habitat restoration at [Robinson Preserve](https://www.mymanatee.org/departments/parks___natural_resources/parks__preserves___beaches/robinson_preserve), a 682-acre area with a variety of restored fisheries nursery habitat, contributes juvenile sport fish to adult populations in the greater Tampa Bay area. The contribution of juveniles is a major information gap that exists for many habitat restoration projects, despite being a realistic metric for evaluating restoration success. With the help of [Manatee County Department of Parks and Natural Resources](https://www.mymanatee.org/departments/parks___natural_resources) and the [National Oceanic and Atmospheric Administration Office of Habitat Conservation](https://www.fisheries.noaa.gov/about/office-habitat-conservation), researchers at the [Florida Fish and Wildlife Research Institute](https://myfwc.com/research/) are seeking to fill this information gap by tagging and tracking the movement of juvenile sport fishes from and within Robinson Preserve.

::: {.light-mode layout-ncol="4" style="text-align: center; justify-content: center; align-items: center;"}
### `r icon_style(fontawesome("tower-broadcast", style = "solid"), scale = 4)` {style="color: white;"}

<font size="+3">13</font>\
Receivers Placed

### `r icon_style(fontawesome("download", style = "solid"), scale = 4, 'text-align'="center")`

<font size="+3">2</font>\
Data Downloads

### `r icon_style(fontawesome("fish-fins", style = "solid"), scale = 4)`

<font size="+3">48</font>\
Fishes Identified

### `r icon_style(fontawesome("tag", style = "solid"), scale = 4)`

<font size="+3">26</font>\
Fish Tagged
:::

::: {.dark-mode layout-ncol="4" style="text-align: center; justify-content: center; align-items: center;"}
### `r icon_style(fontawesome("tower-broadcast", style = "solid"), fill = "white", scale = 4)`

<font size="+3">13</font>\
Receivers Placed

### `r icon_style(fontawesome("download", style = "solid"), fill = "white", scale = 4, 'text-align'="center")`

<font size="+3">2</font>\
Data Downloads

### `r icon_style(fontawesome("fish-fins", style = "solid"), fill = "white", scale = 4)`

<font size="+3">48</font>\
Fishes Identified

### `r icon_style(fontawesome("tag", style = "solid"), fill = "white", scale = 4)`

<font size="+3">26</font>\
Fish Tagged
:::
