---
title: Our Methods in Robinson Preserve
---

A total of 7 acoustic receivers were placed in various
waterbodies within Robinson Preserve; another 6 receivers were placed outside
the preserve, generally targeting known and suspected egress points. At each of
these 13 receivers, water loggers were also installed to track water
temperature and salinity in near real-time. The data are stored within the water
loggers and acoustic receivers until the data are downloaded, approximately
every 3 to 4 months.

In spring (April/May) and fall (Oct/Nov) of 2022 and 2023, we
will implant sport fish with acoustic tags. The goal is to tag up to 40 fish in
2022 and another 40 in 2023. These tags can last up to two years, so we will be
listening for these fish through 2024. While monitoring these fishes, we will
look for the number of 'pings' within the various waterbodies to see how fish
are using the different waterbodies and nursery habitats, as well as 'pings'
outside the preserve, which indicates functionality of the nursery habitats as fish
have emigrated from the nursery habitat to the adult habitats in Tampa Bay and nearby
waters.




