---
title: "Robinson Preserve"
sidebar: false
---

[Robinson Preserve](https://www.mymanatee.org/departments/parks___natural_resources/parks__preserves___beaches/robinson_preserve) is a 682-acre restored area located on the southern shore of Tampa Bay. The preserve is positioned approximately five miles east of the Gulf of Mexico and is adjacent to the mouth of the Manatee River, Perico Bayou, and Palma Sola Bay. Historically, the area consisted of coastal wetlands, but these wetlands were drained in the 1920s to allow for agricultural and human use. Multi-agency restoration efforts began in 2003 with the goal to restore the historical hydrology (i.e., water flow) of the area and provide nursery habitat for recreationally important sport fish in the Tampa Bay estuary.

Hydrological restoration allowed coastal wetland vegetation communities to become reestablished. Robinson Preserve now contains a variety of estuarine habitats, including mangrove-lined creeks and salt marshes, that are critical nursery habitats for many sport fish species. The structure of these vegetation communities protects young fish from predators and provides high prey availability. Young-of-the-year (recently hatched and recruited fish) and juvenile Common Snook (*Centropomus undecimalis*), Red Drum (*Sciaenops ocellatus*), Spotted Seatrout (*Cynoscion nebulosus*), and Atlantic Tarpon (*Megalops atlanticus*) have all been observed in Robinson Preserve.

In 2021, an expansion of Robinson Preserve created multiple waterbodies with unique characteristics such as variation in depth and tidal connections, that may affect their performance as nursery habitat for sport fish. These waterbodies were ultimately connected with the Tampa Bay estuary with the intent to provide fisheries nursery habitat, but for a nursery habitat to be truly functional, sub-adult fish must move away (or emigrate) from juvenile to sub-adult and adult habitats.

**The main goal of this study is to determine if the restored habitats are providing sub-adult fish to the Tampa Bay fishery.** To do this, we will use acoustic telemetry to track fish. Sport fish within Robinson Preserve will be implanted with an acoustic (sound) transmitter and we will set up listening stations (i.e., receivers) in and around the preserve to record when tagged fish swim by. If waterbodies within Robinson Preserve are acting as nursery habitats and supplying fish to the sub-adult and adult population, we should eventually detect acoustically tagged fish with receivers located outside the preserve boundary. We can also use telemetry data to examine how juvenile sportfish use different waterbodies within the preserve, determine which corridors are most effective for emigration, and look for differences in habitat use among species. The information obtained from this study will be useful for future restoration design and construction.
