---
title: Seventh Data Download
author: Jon Peake
date: "03/24/2024"
sidebar: false
---

On February 27th and 29th, FWRI staff recovered data from 9 out of the 11 acoustic receivers deployed in and around Robinson Preserve. Our acoustic receivers revealed an additional 500,000 detections, including detections from 24 of the 57 fish that have been tagged since April 2022. Several fish continue to be detected on receivers located outside the preserve.

Unfortunately, our Mead Point #3 receiver was lost when the line securing it to its location became frayed and snapped after repeated exposure to fast, shifting currents. Because this receiver was at a key location to detect fishes exiting the preserve, the decision was made to replace the missing receiver with an existing receiver from within the preserve. The existing receiver comes from Pond 4, which has a limited connection to other ponds and currently no active acoustic tags. Moving this receiver will allow us to continue monitoring the contribution of Robinson Preserve to adult fish populations while adapting to the challenges of conducting field research.

We are also testing custom-built temperature loggers, ten of which were placed around the preserve during in November 2023. In our first phase of testing, we were successfully able to download temperature data from four out of the ten loggers. FWRI staff will continue to troubleshoot, repair, and test the remaining loggers over the next few months. Furthermore, data will be shared with students from Manatee School for the Arts to practice data analysis and apply scientific concepts in a practical way.

Staff were also able to capture and tag an additional seven fish, including two Atlantic Tarpon and five Common Snook.
